name: Create Binaries and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag for the release (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Install ALSA
        run: sudo apt-get install libasound2-dev
      - name: Create Executable
        id: pyinstaller_linux
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'JParty.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'JParty_linux'
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: JParty_linux
          path: dist/JParty_linux # Assuming the output is in dist/ and renamed

  windows-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        id: pyinstaller_windows
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'JParty.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'JParty_windows'
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: JParty_windows
          path: dist/JParty_windows.exe # Assuming .exe for windows

  macos-arm-build:
    runs-on: macos-latest
    steps:
      - name: Create Executable
        id: pyinstaller_macos_arm
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'JParty.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'JParty_macos_arm'
      - name: Upload macOS ARM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: JParty_macos_arm
          path: dist/JParty_macos_arm # Assuming no extension for macos

  release:
    needs: [linux-build, windows-build, macos-arm-build]
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: Release ${{ github.event.inputs.tag }}
          body: |
            Automated release for version ${{ github.event.inputs.tag }}.
            See the assets below for various platform builds.
          draft: false
          prerelease: false
          files: artifacts/*/* # This will attach all files downloaded into the artifacts directory